In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
'''!nvidia-smi'''

'!nvidia-smi'

## Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as int
scalar.item()

7

In [ ]:
# Vector

vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

In [ ]:
# ndim = number of square brackets (not including closing)
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [ ]:
MATRIX[0,1] # matrix indexing

tensor(8)

In [ ]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Scalar, Vector: lower case </br>
Matrix, Tensor: upper case

In [ ]:
#@title Random Tensors

random_tensor = torch.randn(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[ 0.9573,  0.5893, -0.3871,  0.2801],
         [-0.6244, -1.0716,  0.7149,  1.0503],
         [-1.3750,  1.3867, -1.2128, -0.0446]]),
 torch.float32)

```torch.randn``` generates random number $\sim \mathcal{N}(0,1)$ </br>
```torch.rand``` generates random number $\sim U[0,1)$

In [ ]:
random_image_size_tensor = torch.rand((256,256,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim
# plt.imshow(random_image_size_tensor)

(torch.Size([256, 256, 3]), 3)

In [ ]:
#@title Zeros and ones

zeros = torch.zeros(size=(3,4), dtype=torch.int) # create 3x4 zeros tensor of int32 type
zeros, zeros.dtype

(tensor([[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]], dtype=torch.int32),
 torch.int32)

In [ ]:
ones = torch.ones(size=(3,4))
ones, ones.dtype


(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
#@title Creating a range and tensor-like


In [ ]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# return tensors filled with zeros/ones in the same shape as the input

ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#@title Tensor datatypes

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device


(torch.Size([3]), torch.float32, device(type='cpu'))

#### The three big things in a tensor: ```shape```, ```dtype```, ```device```

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7862, 0.1874, 0.2659, 0.0987],
        [0.0800, 0.3137, 0.3919, 0.9872],
        [0.2548, 0.8274, 0.6106, 0.8707]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
#@title Manipulating tensors


```tensor.add()```, ```tensor.multiply()```

In [ ]:
tensor = torch.tensor([1,2,3])
print("Sum with 10: ", tensor+10)
print("Subtract with 10: ", tensor-10)
print("Multiply with 10: ", tensor * 10)

Sum with 10:  tensor([11, 12, 13])
Subtract with 10:  tensor([-9, -8, -7])
Multiply with 10:  tensor([10, 20, 30])


In [ ]:
print("Hadamard product: ", tensor * tensor)

Hadamard product:  tensor([1, 4, 9])


In [ ]:
print("Dot product: ", torch.matmul(tensor, tensor).item())

Dot product:  14


or you can do ```tensor @ tensor```

In [ ]:
# Matrix multiplication
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.tensor([[2,2],[4,4],[6,6]])
t3 = t1 @ t2
print(t3)
print("Shape:", t1.shape, t2.shape, t3.shape)

tensor([[28, 28],
        [64, 64]])
Shape: torch.Size([2, 3]) torch.Size([3, 2]) torch.Size([2, 2])


In [ ]:
# Transpose

t3t = t3.T
print(t3t)

tensor([[28, 64],
        [28, 64]])


In [ ]:
torch.mm(t1, t2)

tensor([[28, 28],
        [64, 64]])

In [ ]:
#@title Aggregation
x = torch.arange(0,100,10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#print(f"Mean: {x.mean()}") # this will error, doesn't work with int dtype
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# Find positions with max min with argmax, argmin

# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [ ]:
# Change datatype to something else
tensor_float = tensor.type(torch.float16)
tensor_float

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
#@title Reshaping, stacking, squeezing and unsqueezing




Method	One-line description
torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape(). </br>
torch.Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.</br>
torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.</br>
torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.</br>
torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.</br>
torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [ ]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped = x.reshape([1,10]) # turn into 2D array
x_reshaped

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x.reshape([10,1]) # turn into column vector

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x.reshape([2,5]) # turn into any shape, the total has to be equal

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Change view (keeps same data as original but changes view)
# because a view of a tensor shares the same memory slot as the original tensor
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 10)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [ ]:
z[:,0] = 5 # change an element of z
z, x

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

basically, a view is just a tensor in another view, if you change a value of a view, it changes the original, too!

In [ ]:
# stack a tensor on top of another (dim=0 means stack vertically, dim=1 stacks horizontally)

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [ ]:
# Remove all single dimension from a tensor ("sqeeze" the ones)

comp_tensor = torch.rand((1,2,1,3))
print(comp_tensor.squeeze().shape)

# Adding a 1-dimension

print(comp_tensor.unsqueeze(dim=4).shape)

torch.Size([2, 3])
torch.Size([1, 2, 1, 3, 1])


In [ ]:
# rearrange the order of axis values with permute

# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order, NOTE: this is a view
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
#@title Indexing
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#@title Reproducibility

import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D


Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
a = torch.tensor([[[1,2,3],[4,5,6]]])
a.shape

torch.Size([1, 2, 3])

In [ ]:
a.T.shape

<ipython-input-66-f81a2f2e0289>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3571.)
  a.T.shape


torch.Size([3, 2, 1])

In [ ]:
torch.rand((3,4,5)).shape

torch.Size([3, 4, 5])

In [ ]:
a = torch.rand((3,4,5))
b = torch.rand((3,4,5))
torch.matmul(a, b.T)

RuntimeError: ignored