<a href="https://colab.research.google.com/github/andythetechnerd03/PyTorch_Learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
x

tensor([[1.9280e-02, 3.3438e-01, 8.7542e-01, 6.2782e-01, 8.3513e-01, 4.8486e-01,
         1.3772e-01],
        [6.0855e-01, 7.3812e-01, 2.3807e-01, 9.6988e-01, 3.7441e-01, 8.9269e-01,
         5.2226e-01],
        [3.8655e-01, 4.7005e-01, 5.1121e-01, 4.0779e-01, 2.8201e-01, 7.5083e-01,
         2.2802e-01],
        [9.1847e-02, 1.9111e-01, 2.9585e-01, 5.5404e-01, 2.8813e-01, 1.8566e-01,
         6.0374e-04],
        [1.4936e-01, 6.3377e-01, 6.0380e-01, 9.6168e-01, 4.4430e-01, 7.0485e-01,
         6.8734e-01],
        [6.7066e-01, 4.3888e-01, 3.4545e-01, 2.7086e-01, 4.4843e-01, 2.4515e-01,
         8.8425e-01],
        [1.9608e-01, 5.1796e-01, 5.3962e-01, 2.6257e-01, 6.9390e-02, 1.4545e-02,
         3.2927e-01]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
y = torch.rand(1,7)

# Perform matrix multiplication
x @ y.T

tensor([[0.9422],
        [1.0788],
        [0.9087],
        [0.4172],
        [1.1290],
        [0.5693],
        [0.4515]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)
x = torch.rand(7,7)

torch.manual_seed(random_seed)
y = torch.rand(1,7)

# Create two random tensors


# Matrix multiply tensors
x @ y.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
random_seed = 1234


# Check for access to GPU
print(torch.cuda.is_available())
# Create two random tensors on GPU
torch.cuda.manual_seed(random_seed)
a = torch.rand(2,3).to('cuda')

torch.cuda.manual_seed(random_seed)
b = torch.rand(2,3).to('cuda')

a,b

True


(tensor([[0.2823, 0.6816, 0.9152],
         [0.3971, 0.8742, 0.4194]], device='cuda:0'),
 tensor([[0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
result = a @ b.T
result, result.shape

(tensor([[0.8386, 0.5860],
         [1.0676, 0.5279]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
print(torch.max(result).item())
# Find min
print(torch.min(result).item())


1.0675687789916992
0.5279417037963867


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find max
print(torch.argmax(result))
# Find min
print(torch.argmin(result))

tensor(2, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [17]:
# Set seed

torch.cuda.manual_seed(7)


# Create random tensor
t = torch.rand((1,1,1,10))

# Remove single dimensions
t = t.squeeze()

# Print out tensors and their shapes
t, t.shape

(tensor([0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298, 0.7231, 0.7423,
         0.5263]),
 torch.Size([10]))